apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-nzck
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-abcn-tenant/rhtap-demo-app/hacbs-test-project-nzck@sha256:8c8f88c3ac808d853636f50d830bb6d775dc8b5a5f6049aa0cf7190fe82d6e49
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
