apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-nzck
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-abcn-tenant/rhtap-demo-app/hacbs-test-project-nzck@sha256:c41146ee66170fdb5b4bf862d51b4f3e505db8d25381d023d30da8afeb2055b1
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
