apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-nzck
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-abcn-tenant/rhtap-demo-app/hacbs-test-project-nzck@sha256:8dc3bed51016f99923b54b6b18dd907683a58a314eb7befc9a7fb78eded11940
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
